name: code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make coverage
      run: make coverage
    - name: coverage
      id: coverage
      # Generates a GitHub Workflow output named `coverage`
      run: |
        COVERAGE="$( bash ./tests/coverage.sh )"
        echo "##[set-output name=coverage;]${COVERAGE}%"
