name: code coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
    - name: make coverage
      run: make coverage
